# Generated by Django 3.1.4 on 2020-12-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'opened'), (1, 'returned'), (2, 'closed'), (3, 'expects')], default=0),
        ),
    ]
