# Generated by Django 3.1.3 on 2020-11-17 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20201109_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users_Order',
            new_name='User_to_Order',
        ),
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Stack_to_Order',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
