# Generated by Django 3.1.3 on 2020-11-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201117_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
