# Generated by Django 3.1.3 on 2020-11-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201124_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='HeyWork/static/Default_avatar.jpg', upload_to=''),
        ),
    ]
