# Generated by Django 3.1.3 on 2020-11-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201124_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/Default_avatar.jpg', upload_to=''),
        ),
    ]
