# Generated by Django 3.1.3 on 2020-11-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201124_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stack_to_User',
        ),
    ]
