# Generated by Django 3.1.3 on 2020-11-24 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_delete_stack_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='user',
            field=models.ManyToManyField(related_name='stack', to=settings.AUTH_USER_MODEL),
        ),
    ]
