# Generated by Django 3.1.3 on 2020-11-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201124_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
