# Generated by Django 3.1.3 on 2020-11-24 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_auto_20201124_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='user',
            field=models.ManyToManyField(related_name='technology', to=settings.AUTH_USER_MODEL),
        ),
    ]
