# Generated by Django 3.1.3 on 2020-11-24 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_auto_20201124_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ManyToManyField(through='app.User_to_Order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
