# Generated by Django 3.1.3 on 2020-11-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201124_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isComplete',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'opened'), (1, 'returned'), (2, 'closed')], default=0),
        ),
    ]
