# Generated by Django 3.1.3 on 2020-11-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201124_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_to_order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='user_to_order',
            old_name='executor_id',
            new_name='executor',
        ),
        migrations.RenameField(
            model_name='user_to_order',
            old_name='order_id',
            new_name='order',
        ),
    ]
