# Generated by Django 3.1.4 on 2020-12-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201130_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/default_avatar.jpg', upload_to='static'),
        ),
    ]
