# Generated by Django 3.1.4 on 2020-12-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201203_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/default_avatar.jpg', upload_to='static'),
        ),
    ]
