# Generated by Django 3.1.4 on 2020-12-03 14:05

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201203_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to=''),
        ),
    ]
